const productsData = [
  {
    slug: "product-1",
    title: "Product 1",
    content: "Details about Product 1",
    image: "/images/products/pd1.webp",
    date: "2023-01-01",
    client: "Client 1",
    year: "2023",
    role: "Frontend Developer",
    url: "/products/product-1",
  },
  {
    slug: "product-2",
    title: "Product 2",
    content: "Details about Product 2",
    image: "/images/products/pd2.webp",
    date: "2023-02-01",
    client: "Client 2",
    year: "2023",
    role: "Backend Developer",
    url: "/products/product-2",
  },
  {
    slug: "product-3",
    title: "Product 3",
    content: "Details about Product 3",
    image: "/images/products/pd3.webp",
    date: "2023-03-01",
    client: "Client 3",
    year: "2023",
    role: "Full Stack Developer",
    url: "/products/product-3",
  },
  {
    slug: "product-4",
    title: "Product 4",
    content: "Details about Product 4",
    image: "/images/products/pd4.webp",
    date: "2023-03-01",
    client: "Client 4",
    year: "2023",
    role: "Full Stack Developer",
    url: "/products/product-4",
  },
  {
    slug: "product-5",
    title: "Product 5",
    content: "Details about Product 5",
    image: "/images/products/pd5.webp",
    date: "2023-01-01",
    client: "Client 4",
    year: "2023",
    role: "Frontend Developer",
    url: "/products/product-5",
  },
  {
    slug: "product-6",
    title: "Product 6",
    content: "Details about Product 6",
    image: "/images/products/pd6.webp",
    date: "2023-02-01",
    client: "Client 2",
    year: "2023",
    role: "Backend Developer",
    url: "/products/product-6",
  },
  {
    slug: "product-7",
    title: "Product 7",
    content: "Details about Product 7",
    image: "/images/products/pd7.webp",
    date: "2023-03-01",
    client: "Client 3",
    year: "2023",
    role: "Full Stack Developer",
    url: "/products/product-7",
  },
  {
    slug: "product-8",
    title: "Product 8",
    content: "Details about Product 8",
    image: "/images/products/pd8.webp",
    date: "2023-03-01",
    client: "Client 4",
    year: "2023",
    role: "Full Stack Developer",
    url: "/products/product-8",
  },
  {
    slug: "product-9",
    title: "Product 9",
    content: "Details about Product 9",
    image: "/images/products/pd9.webp",
    date: "2023-01-01",
    client: "Client 1",
    year: "2023",
    role: "Frontend Developer",
    url: "/products/product-9",
  },
  {
    slug: "product-10",
    title: "Product 10",
    content: "Details about Product 10",
    image: "/images/products/pd10.webp",
    date: "2023-02-01",
    client: "Client 2",
    year: "2023",
    role: "Backend Developer",
    url: "/products/product-10",
  },
  {
    slug: "product-11",
    title: "Product 11",
    content: "Details about Product 11",
    image: "/images/products/pd11.webp",
    date: "2023-03-01",
    client: "Client 3",
    year: "2023",
    role: "Full Stack Developer",
    url: "/products/product-11",
  },
  {
    slug: "product-12",
    title: "Product 12",
    content: "Details about Product 12",
    image: "/images/products/pd12.webp",
    date: "2023-03-01",
    client: "Client 4",
    year: "2023",
    role: "Full Stack Developer",
    url: "/products/product-12",
  },
  {
    slug: "product-13",
    title: "Product 13",
    content: "Details about Product 13",
    image: "/images/products/pd13.webp",
    date: "2023-01-01",
    client: "Client 1",
    year: "2023",
    role: "Frontend Developer",
    url: "/products/product-13",
  },
  {
    slug: "product-14",
    title: "Product 14",
    content: "Details about Product 14",
    image: "/images/products/pd14.webp",
    date: "2023-02-01",
    client: "Client 2",
    year: "2023",
    role: "Backend Developer",
    url: "/products/product-14",
  },
  {
    slug: "product-15",
    title: "Product 15",
    content: "Details about Product 15",
    image: "/images/products/pd14_1.webp",
    date: "2023-03-01",
    client: "Client 3",
    year: "2023",
    role: "Full Stack Developer",
    url: "/products/product-15",
  },
  {
    slug: "product-16",
    title: "Product 16",
    content: "Details about Product 16",
    image: "/hero4.jpg",
    date: "2023-03-01",
    client: "Client 4",
    year: "2023",
    role: "Full Stack Developer",
    url: "/products/product-16",
  },
];

export default productsData;
